parameters:
  - name: DependsOn
    type: object
    default: []

jobs:
  - job: versioning
    displayName: ğŸ·ï¸ Versioning
    ${{ if ne(parameters.DependsOn, '')}}:
      dependsOn: ${{ parameters.DependsOn }}
    steps:
      - task: gitversion/execute@0
        inputs:
          additionalArguments: "/updateprojectfiles"
